GET http://localhost:3333/v1/transactions

###
GET http://localhost:3333/v1/transactions/3a36c4bd-6462-4132-8c28-6e5712ddd3a4

###
GET http://localhost:3333/v1/transactions/summary

###
POST http://localhost:3333/v1/transactions
Content-Type: 'application/json'

{
  "title": "Freelancer DB",
  "amount": 10,
  "type": "credit"
}